/**
 * help-content.js
 * Auto-generated help content from markdown files
 * DO NOT EDIT THIS FILE DIRECTLY - Edit .md files in help/ folder and run build-help.py
 */

const HelpContent = {
    'Creating-Target-Database': `# Create the target database

These scripts are found in the DSO folder. You will also need the Source
folder with the original source files.


## Change History

**v1**
Initial version. Final database content was defined by the header:

\`\`\`
Object	Type	RA	Dec	Const	Common	Other
\`\`\`

**v2**
Added additional information to the database, defined by the header:

\`\`\`
Object	Type	RA	Dec	Const	Mag	Subr	Size_max	Size_min	Common	Other
\`\`\`

**v3**
Added new field to the database, "Catalogue". New header:

\`\`\`
Object	Catalogue	Type	RA	Dec	Const	Mag	Subr	Size_max	Size_min	Common	Other
\`\`\`

    * Object: Designator (M 31, NGC 5323, etc.)
    * Catalogue: Messier, NGC, IC, etc.)
    * Type: Type of object
    * RA: Right Ascension
    * Dec: Declination
    * Const: Constellation
    * Mag: Brightness magnitude
    * Subr: Surface brightness (only for galaxies)
    * Size_max: Major axis (arc minutes)
    * Size_min: Minor axis (arc minutes)
    * Common: Common name(s), if any (Crab Nebula, etc.)
    * Other: Other name(s), if any

The scripts *process_raw_openngc.py*, *process_raw_sac.py*, *validate.py*
were updated to automatically add the new 'catalogue' field and contents
when converting from the original TXT format into CSV file. The remaining
existing files containing other catalogs or updated information were
updated with the new field and contents.

Changed mapping of some objects and annotated docs that some types never
show up because we're using OpenNGC as the baseline. The other databases
add information only if it is missing from the OpenNGC database.

**v4**

Added multiple command-line options in **scrubber.py** to provide more
flexibility in defining which catalogs to keep in the database and which to
not keep.

Fixed bug where the --fill option was not doing reciprocal copies to the
object in different catalogs


**v5**

Added --to-extra <catalog-list> command line option to
**scrubber.py**. This option condenses the specified catalogs into a
virtual catalog named "Extra". This reduces the number of catalogs with a
small number of objects to make it easier to select the desired catalogs
for filtering.


## Summary

There are two foundation data sources (openngc & SAC). Other catalogues or
miscellaneous additions or modifications are manually created in CSV.


**Steps**

    * Convert the two base files (openngc & SAC) in "txt" format to CSV (comma
      separated value) files.
    * Convert the openngc_addendum to CSV.
    * Validate all CSV files.
    * Merge by using one database (openngc) as the original and then
      adding, or updating, with the other databases.
    * Validate the final output (final_targets.csv)
    * Import CSV database

## Detailed Instruction

We use the merge.py script, which requires a target file to be designated
the primary file and other input files to be designated as secondary
files. The primary file is used as the baseline and the secondary files add
only those things that the primary file does not have.

But first, we have to create the initial primary and secondary files. The
two initial target sets that we use come from the OpenNGC project and the
SAC project. The OpenNGC data seems to be more current than the SAC
database.

The baseline is openngc.csv. All others are merged into the final database
using that as the foundation. This means that the secondary databases
contribute to the final database only if openngc.csv is missing
information.

We use the SAC type mappings, but some of the SAC types are not to be found
in the final database because OpenNGC classified them
differently. misc_addendum.csv can be used to add new information to the
existing baseline as it becomes available. Put misc_addendum.csv as the
last file to be merged.

The interim working files are tab-separated. The final output is a comma
separated file with double quote delimiters.

To clean up the database, reduce duplication, and populate the data fields
as much as possible, there is another utility called **scrubber.py**.


## Running the scripts

Note that these scripts run in the linux environment and require
Python. However, creating a Windows script is trivial if Python is
installed.

\`\`\`
./1-process-validate.sh*
./2-do-merge.sh*
./3-do-scrubber.sh*
\`\`\`

## Example Scripts

**bin/1-process-validate.sh**

\`\`\`
#!/bin/bash

python bin/process_raw_openngc.py ../Source/openngc.txt > openngc.csv
python bin/process_raw_openngc.py ../Source/openngc_addendum.txt > openngc_addendum.csv
python bin/process_raw_sac.py ../Source/SAC_DeepSky_Ver81_Fence.TXT > sac.csv

python bin/validate.py openngc.csv
python bin/validate.py openngc_addendum.csv
python bin/validate.py sac.csv
python bin/validate.py manual/ic_addendum.csv
python bin/validate.py manual/messier_addendum.csv
python bin/validate.py manual/caldwell.csv
python bin/validate.py manual/misc_addendum.csv
\`\`\`


**bin/2-do-merge.sh**


\`\`\`
#!/bin/bash


# merge all csv files and then scrub to produce the final CSV for import

python bin/merge.py  \\
    -p openngc.csv \\
    -s openngc_addendum.csv sac.csv manual/ic_addendum.csv manual/messier_addendum.csv manual/caldwell.csv manual/misc_addendum.csv \\
    > temp_dso.csv

rm -f openngc.csv openngc_addendum.csv sac.csv
\`\`\`


**bin/3-do-scrubber.sh**

\`\`\`
#!/bin/bash


# scrubber.py - perform various operations to distribute accurate data and
# to delete duplicate records.

# --in read from the specified input file
# --out output to the specified output file
# --log log to file
# --create-missing create missing records that are cross-referenced from other targets
# --fill fill empty fields from cross-referenced targets in other catalogs
# --prefer use the preferred catalogs, in specified order, for --fill
# --dupe-size if only one size field is filled, copy the value to the other
# --to-extra send the specified catalogs to the virtual Extra list
# --keep keep only the specified catalogs
# --dedupe-from delete records that are duplicates of each other from the specified catalogs
#      --dedupe-from "NGC,IC,UGC,RCW,vdB,Pal"



python bin/scrubber.py \\
       --in temp_dso.csv \\
       --out final_targets.csv \\
       --log scrubber.log \\
       --create-missing \\
       --fill \\
       --prefer "NGC,IC,PK,UGC,Pal,Sharpless,RCW,vdB,Abell,Arp,Caldwell,Barnard,Messier" \\
       --dupe-size \\
       --to-extra "Pal,RCW,vdB" \\
       --keep "Abell,Arp,Barnard,Caldwell,Extra,IC,Messier,NGC,Sharpless"


rm temp_dso.csv

echo
echo "Import final_targets.csv after clearing existing target database"
echo
\`\`\`
`,

    'best-months': `# Best Month Calculation

## Overview

Calculates the **best observing month** for each target using a sophisticated two-criteria weighted scoring system. The algorithm evaluates every day of the year to find when a target is most favorably positioned for astrophotography.

## How Best Month is Calculated

### Two Scoring Criteria

The best month calculation uses two independent scores that are combined with type-specific weights:

#### 1. Transit Score (How Close to Midnight)

The transit score measures how close the target's transit time is to local midnight.

**Why this matters:** Targets that transit near midnight are observable for the longest period during a single night. Targets that transit at dawn or dusk have very limited imaging windows.

**Calculation:**
- For each day, calculate when the target transits (reaches its highest point in the sky)
- Measure distance from midnight: \`min(|hour - 0|, |hour - 24|)\`
- Convert to score: \`1 - (distance / 12)\`
  - Transit at midnight = 1.0 (perfect)
  - Transit at noon = 0.0 (worst)
  - Transit at 6 PM or 6 AM = 0.5

#### 2. Dark Hours Score (How Much Imaging Time)

The dark hours score measures how many hours the target is above its altitude threshold during astronomical darkness.

**Why this matters:** More dark hours means more imaging time. Targets benefit from longer nights (winter) and from being positioned favorably in the sky during darkness.

**Calculation:**
- For each day, sample altitude every 10 minutes during astronomical darkness (sun below -18°)
- Count accumulated hours when target is above its type-specific altitude threshold
- Find the maximum dark hours across the entire year
- Normalize each day's dark hours: \`darkHours / maxDarkHours\`
  - Day with most dark hours = 1.0 (perfect)
  - Day with no dark hours = 0.0

### Type-Specific Weights

Different target types prioritize these criteria differently based on their observational requirements:

| Type | Transit Weight | Dark Hours Weight | Min Altitude |
|------|----------------|-------------------|--------------|
| **Stars & Asterisms** | 75% | 25% | 40° |
| **Dark Nebulae** | 70% | 30% | 40° |
| **Reflection Nebulae** | 70% | 30% | 40° |
| **Galaxies** | 70% | 30% | 40° |
| **Galaxy Clusters** | 65% | 35% | 40° |
| **Open Clusters** | 65% | 35% | 40° |
| **Globular Clusters** | 65% | 35% | 40° |
| **Planetary Nebulae** | 60% | 40% | 30° |
| **Cluster + Nebula** | 60% | 40% | 30° |
| **Bright Nebulae** | 55% | 45% | 30° |
| **Supernova Remnants** | 55% | 45% | 30° |
| **Other** | 60% | 40% | 30° |

**Rationale:**
- **High transit weight** (stars, dark nebulae, galaxies): These targets benefit most from being high in the sky. Position matters more than total time.
- **Balanced weights** (bright nebulae, SNRs): These extended objects benefit from both good positioning and longer integration time.
- **Lower altitude thresholds** (bright nebulae): Brighter objects can be imaged at lower altitudes where atmospheric extinction is greater.

### Final Score Calculation

For each day of the year:

\`\`\`
score = (transitScore × transitWeight) + (darkHoursScore × darkHoursWeight)
\`\`\`

The day with the **highest score** determines the best month.

**Example:**

For a dark nebula (70% transit / 30% dark hours):
- Day in December: Transit at 11 PM (score 0.92), 8.5 dark hours (score 0.95)
  - Final: \`(0.92 × 0.70) + (0.95 × 0.30) = 0.929\`
- Day in June: Transit at midnight (score 1.0), 3.2 dark hours (score 0.36)
  - Final: \`(1.0 × 0.70) + (0.36 × 0.30) = 0.808\`

December wins despite June having perfect transit time, because the much longer dark hours in December overcome the slight transit disadvantage.

## Why Some Targets Have No Best Month

Approximately 24% of targets will have **null** (no best month) for a given location. This happens when a target is **never observable** from that location under reasonable conditions.

### Reason 1: Peak Altitude Too Low (Most Common)

Every target type has a minimum altitude threshold (30° or 40°). If a target's **peak altitude** (when it transits) never reaches this threshold, it cannot be observed well from your location.

**Peak altitude** depends only on:
- Your latitude
- Target's declination
- Your artificial horizon profile

**Formula:** \`peakAltitude = 90° - |latitude - declination|\`

**Example:**
- Location: Home (39°N)
- Target: Abell 1060 (declination -27.5°)
- Peak altitude: \`90° - |39° - (-27.5°)| = 90° - 66.5° = 23.5°\`
- Threshold for galaxy cluster: 40°
- Result: **null** (never gets high enough)

**Common scenarios:**
- **Southern hemisphere objects from northern locations** (and vice versa)
- Objects with extreme declinations that barely rise above horizon
- Circumpolar objects that never rise (for objects near the opposite celestial pole)

### Reason 2: Never in Darkness

Even if a target reaches sufficient altitude, it may **never be above the threshold during astronomical darkness** on any day of the year.

**Why this happens:**
- **Sun proximity:** Target is always near the sun seasonally (e.g., transits during daylight all year)
- **Summer circumpolar targets:** At high latitudes, summer months may have no astronomical darkness, so circumpolar targets near the zenith have zero dark hours
- **Twilight-only visibility:** Target only rises/sets during twilight periods

**Example:**
A target at +85° declination observed from 45°N latitude:
- Always circumpolar (never sets)
- Always high in sky
- But during June-July, astronomical darkness never occurs
- If target's only high-altitude time is during these months → **null**

### Null Statistics

For a typical northern mid-latitude location (35-45°N):
- **~76% of targets** have valid best months
- **~24% are null** (not observable)

The null rate varies by latitude:
- **Equatorial locations** (~0-10°): Lowest null rate (~15%) - can see both hemispheres
- **Mid-latitudes** (~35-45°): Medium null rate (~24%) - miss far southern objects
- **High latitudes** (~55°+): Higher null rate (~30-35%) - miss southern objects + summer darkness issues

## Visibility Window vs Best Month

**Best Month** answers: "When is this target positioned most favorably?"

**Visibility Window** (Start/End months) answers: "During which months can I observe this target at all?"

The visibility window is calculated separately based on:
- Minimum dark hours requirement (default: 3 hours)
- Same altitude thresholds as best month
- Finds the longest continuous sequence of observable days

**Example:**
- Target: M 31 (Andromeda Galaxy)
- Best Month: **October** (transits at midnight, long dark hours)
- Visibility Window: **July through March** (observable, but less ideal in July/March)

You can observe M 31 for many months, but October provides the optimal combination of transit time and dark hours.

## Location Dependency

Best months are **location-specific** because they depend on:

1. **Latitude** - Affects peak altitude and dark hour distribution
2. **Longitude** - Affects local transit time (but usually same month)
3. **Timezone** - Only affects time display, not the month
4. **Artificial horizon** - Blocks low-altitude observations

**Significant differences** between locations occur when:
- Large latitude changes (>20-30°) alter peak altitudes and darkness patterns
- Northern hemisphere vs Southern hemisphere (completely inverts seasons)
- Extreme latitude locations (>60°) have unusual darkness patterns

**Minimal differences** when:
- Same latitude, different longitude (transit time shifts but same month)
- Small latitude changes (<10°) within same hemisphere
- Similar mid-latitude locations within the same continent

## Calculation Parameters

The best month calculation uses these defaults:

- **Sampling:** Every day of the year (can be adjusted with \`DAY_SAMPLING_STEP\`)
- **Time resolution:** 10-minute intervals during darkness (adjustable with \`SAMPLING_INTERVAL_MINUTES\`)
- **Darkness definition:** Astronomical darkness (sun below -18°)
- **Year:** Current calendar year (assumes typical year, not specific year)

## Timestamps and Metadata

When best months are calculated, we store:
- **Calculation timestamp** - When the calculation was performed
- **Location used** - Which observer location was used
- **Altitude parameter** - Minimum altitude threshold used
- **Dark hours parameter** - Minimum dark hours threshold used

This metadata helps you know if recalculation is needed when you change locations or adjust observation parameters.

## Tips for Using Best Month

1. **Best month is a guide, not a rule** - A target may be excellent 2-3 months before/after its best month
2. **Check visibility window** - Tells you the full range of observable months
3. **Consider weather** - Your location's best weather months may not align with astronomical best months
4. **Multi-target sessions** - Different targets have different best months; plan sessions accordingly
5. **Recalculate when traveling** - If you travel >500 miles north/south, recalculate for better accuracy

## Advanced: Algorithm Performance

The calculation is optimized for speed:
- **Calculates** ~365 days × 2 criteria per target
- **Processing time:** ~15-30 seconds for 15,000+ targets
- **Uses transit-based approach:** Simplified from complex window calculations (previous versions took minutes)
- **Memory efficient:** Processes one target at a time

The algorithm is deterministic - running it multiple times with the same parameters produces identical results.
`,

    'help-system': `# Help System - Usage Guide

## Overview

The help system uses markdown files that are bundled into JavaScript for local file access (no web server required).

## Directory Structure

\`\`\`
src/
├── help/                          # Markdown help files (edit these)
│   └── calculate-best-months.md
│   └── build-help.py              # Build script
├── js/
│   └── help-content.js            # Auto-generated (don't edit)
\`\`\`

## Adding New Help Files

1. **Create markdown file** in \`help/\` folder:
   \`\`\`
   help/my-new-feature.md
   \`\`\`

2. **Run build script**:
   \`\`\`bash
   python help/build-help.py
   \`\`\`

   This generates/updates \`js/help-content.js\` with all help content.

3. **Use in code**:
   \`\`\`javascript
   // In your modal setup:
   helpBtn.onclick = () => this.showMarkdownHelp('my-new-feature');
   \`\`\`

   The key matches the filename without \`.md\` extension.

## Editing Existing Help

1. Edit the \`.md\` file in \`help/\` folder
2. Run \`python help/build-help.py\`
3. Refresh your browser

## How It Works

- **Markdown files**: Written in standard markdown, stored in \`help/\`
- **Build script**: Reads all \`.md\` files, converts to JavaScript strings
- **help-content.js**: Contains all help as a JavaScript object
- **marked.js**: Renders markdown to HTML at runtime

## Requirements

- Python 3.x (for build script)
- \`marked.min.js\` in \`include/\` folder
- \`help-content.js\` placed in the \`help/\`

## Script Tag Order in index.html

\`\`\`html
<script src="js/config.js"></script>
<script src="include/marked.min.js"></script>    <!-- Markdown renderer -->
<script src="js/help-content.js"></script>        <!-- Help content -->
<script src="js/ui-manager.js"></script>          <!-- Uses HelpContent -->
\`\`\`

## Benefits

- ✅ Works with \`file://\` protocol (no web server needed)
- ✅ Edit markdown files directly
- ✅ One command to rebuild
- ✅ All help content in one file (fast loading)
- ✅ Easy to add new help topics

## Notes

- Don't edit \`js/help-content.js\` directly - it's auto-generated
- Filename becomes the help key (e.g., \`my-help.md\` → \`'my-help'\`)
- Build script must be run after any markdown changes
- Template literals used, so backticks in markdown are escaped automatically
`,

    'scrubber': `# Scrubber.py Documentation

## Overview

\`scrubber.py\` is a CSV-based astronomical target database utility that processes deep sky object catalogs with cross-referencing capabilities. It manages relationships between objects through the "Other" field, fills missing data from related records, handles deduplication, and maintains bidirectional references.

## Command-Line Options

### Input/Output

**\`--in <filepath>\`** (optional)
- Input CSV file path
- If not specified, reads from **stdin**
- Allows piping between scrubber instances

**\`--out <filepath>\`** (optional)
- Output CSV file path
- If not specified, writes to **stdout**
- Allows piping between scrubber instances

**\`--log <filepath>\`** (optional)
- Log file for operational details
- Operational output written to log file (overwrite mode)
- Statistics written to stdout
- Without --log, operations run silently

### Operations

**\`--create-missing\`**
- Creates records for objects referenced in "Other" fields but not present in database
- Establishes **bidirectional references** automatically
- If A references B, ensures B references A back
- Essential for proper cross-referencing before --fill

**\`--fill\`**
- Fills empty fields via cross-referencing through "Other" field
- Uses --prefer list to resolve conflicts when both records have values
- Merges common names from all referenced objects
- Merges Other fields to maintain complete cross-references

**\`--dupe-size\`**
- Copies non-empty size value to empty size field
- If \`Size_min\` is empty and \`Size_max\` is 13.8, copies 13.8 to \`Size_min\`
- If \`Size_max\` is empty and \`Size_min\` is 5.7, copies 5.7 to \`Size_max\`
- Only fills empty fields; leaves existing values unchanged

**\`--prefer <catalog_list>\`**
- Comma-separated list of catalogs in accuracy priority order
- Example: \`"NGC,IC,PK,UGC,Messier"\`
- **Only applies when BOTH records have values for the same field**
- Empty fields are filled from any source regardless of priority
- Higher priority (earlier in list) = more trusted data source
- Required when using --dedupe-from

**\`--dedupe-from <catalog_list>\`**
- Comma-separated list of catalogs from which duplicate target records CAN be deleted during deduplication
- Will not delete records from catalogs not in the list
- The <catalog list> itself defines the priority order. Of the catalogs in
  the list, put the most trusted first to allow targets to be deleted first
  from catalogs near the end of the list
- Example: \`--dedupe-from "UGC,PGC"\` will not delete target records from
  NGC/IC/Messier but can remove duplicate records from the UGC/PGC catalogs.
  

**\`--keep <catalog_list>\`**
- Comma-separated list of catalogs to keep
- Deletes all catalogs not in the list
- Runs after all other processing

**\`--statistics\`**
- Generates statistics report
- Can be combined with other operations
- Does not require --out

### Requirements

At least one operation must be specified: \`--create-missing\`, \`--fill\`, \`--dupe-size\`, \`--dedupe-from\`, \`--statistics\`, or \`--keep\`

## CSV File Format

### Fields

- **Object**: Unique identifier (e.g., "NGC 1952", "M 1", "Abell 21")
- **Catalogue**: Catalog name (e.g., "NGC", "Messier", "Abell", "PK")
- **Type**: Object type code (e.g., "PLNNB", "GALXY", "OPNCL")
- **RA**: Right Ascension (decimal hours)
- **Dec**: Declination (decimal degrees)
- **Const**: Constellation (3-letter IAU code)
- **Mag**: Visual magnitude
- **Subr**: Surface brightness
- **Size_max**: Maximum angular size (arc minutes)
- **Size_min**: Minimum angular size (arc minutes)
- **Common**: Common name(s), comma-separated
- **Other**: Comma-separated list of alternate designations

### CSV Format Details

- All fields quoted (QUOTE_ALL)
- Empty fields represented as empty strings \`""\`
- UTF-8 encoding
- Standard CSV with comma delimiter

## Operation Order

Operations execute in this fixed order when multiple options are specified:

1. **--create-missing**: Create records and establish bidirectional references
2. **--fill**: Fill empty fields via cross-referencing
3. **--dupe-size**: Duplicate size values
4. **--dedupe-from**: Remove duplicate records
5. **--keep**: Delete catalogs not in the list

This order ensures:
- Missing records exist before filling
- Bidirectional references exist before filling
- Data is complete before deduplication
- Catalog deletion happens last

## How Operations Work

### Create Missing Records

When A references B in its "Other" field but B doesn't exist:

1. Creates new record for B with Object and Catalogue fields populated
2. Sets B's Other field to reference A
3. After all missing records created, establishes bidirectional references:
   - If A→B, ensures B→A
   - If B→C, ensures C→B
   - Results in fully connected reference graph

**Example:**

Input:
\`\`\`csv
"Abell 21","Abell","","","","","","","","","Medusa Nebula","Sh 2-274"
"PK 205+14.1","PK","PLNNB","7.483","13.25","GEM","11.3","16.4","10","6","","Abell 21"
\`\`\`

After --create-missing:
\`\`\`csv
"Abell 21","Abell","","","","","","","","","Medusa Nebula","Sh 2-274, PK 205+14.1"
"PK 205+14.1","PK","PLNNB","7.483","13.25","GEM","11.3","16.4","10","6","","Abell21,Sh 2-274"
"Sh 2-274","Sh","","","","","","","","","","Abell 21,PK 205+14.1"
\`\`\`

Note: All records now reference each other

### Fill Empty Fields

For each target, examines all objects referenced in its "Other" field:

1. **For empty target fields**: Fills from any source (--prefer not consulted)
2. **For non-empty target fields**: Only overwrites if source has higher priority (per --prefer list)
3. **Common names**: Merges all unique common names from target and all sources
4. **Other fields**: Merges all unique designators to maintain complete cross-reference graph

**Priority Rules:**
- Empty field + any source = **FILL** (ignore priority)
- Non-empty field + lower priority source = **KEEP** existing
- Non-empty field + higher priority source = **OVERWRITE** with source

**Example:**

After --fill with --prefer "NGC,PK,IC,Messier,Abell":
\`\`\`csv
"Abell 21","Abell","PLNNB","7.483","13.25","GEM","11.3","16.4","10","6","Medusa Nebula","Sh 2-274, PK 205+14.1"
"PK 205+14.1","PK","PLNNB","7.483","13.25","GEM","11.3","16.4","10","6","Medusa Nebula","Abell 21, Sh 2-274"
"Sh 2-274","Sh","PLNNB","7.483","13.25","GEM","11.3","16.4","10","6","Medusa Nebula","Abell 21, PK 205+14.1"
\`\`\`

All three records now have:
- Complete astronomical data (from PK, highest priority with data)
- Merged common name "Medusa Nebula"
- Complete bidirectional cross-references

### Duplicate Size Fields

Simple operation that ensures size consistency:

\`\`\`
If Size_min = "" and Size_max = "13.8" → Size_min = "13.8"
If Size_max = "" and Size_min = "13.8" → Size_max = "13.8"
If both have values → no change
If both empty → no change
\`\`\`

### Deduplicate Records

Removes duplicate records based on cross-references and catalog priority:

**Process:**
1. Identifies groups of objects that reference each other
2. Within each group:
   - Keeps all records from catalogs NOT in --dedupe-from list
   - Will delete duplicate records in catalogs in --dedupe-from list based
     on the order of catalogs in the list. Records are first to be deleted
     from catalogs near the end of the list.


**Example:**

\`\`\`
--dedupe-from "IC,Messier"

Group: NGC 1952 ↔ M 1 ↔ IC 1234
Result: Keeps NGC 1952 only (not in dedupe-from list)

Group: IC 2000 ↔ M 42
Result: Keeps IC 2000 (IC is first in dedupe-from, M comes later in prefer
list so records are deleted from M first)
\`\`\`

### Keep Catalogs

Simple filter applied last:
\`\`\`
--keep "NGC,IC,Messier"
Keeps only: NGC, IC, and Messier catalogs and their records
Discards: All other catalogs and records
\`\`\`

## Usage Examples

### Basic Examples


**Fill empty fields with priority:**
\`\`\`bash
python scrubber.py \\
  --in input.csv \\
  --out output.csv \\
  --fill \\
  --prefer "NGC,IC,Messier"
\`\`\`

**Create missing records and fill:**
\`\`\`bash
python scrubber.py \\
  --in input.csv \\
  --out output.csv \\
  --create-missing \\
  --fill \\
  --prefer "NGC,IC,PK,Messier,Abell"
\`\`\`

**Deduplicate records from specified catalogs:**
\`\`\`bash
python scrubber.py \\
  --in input.csv \\
  --out output.csv \\
  --dedupe-from "IC,UGC,PGC"
\`\`\`

### Piping Examples

**Chain multiple operations:**
\`\`\`bash
python scrubber.py \\
  --in raw_data.csv \\
  --create-missing \\
  --fill \\
  --prefer "NGC,IC,Messier" \\
| python scrubber.py \\
  --out final.csv \\
  --keep "NGC,IC,Messier,Caldwell"
\`\`\`


**Delete catalogs then fill:**
\`\`\`bash
cat large_catalog.csv \\
| python scrubber.py \\
  --keep "NGC,IC" \\
| python scrubber.py \\
  --out filtered_filled.csv \\
  --fill \\
  --prefer "NGC,IC"
\`\`\`

### Complete Workflow Example

**Full processing pipeline with logging:**

\`\`\`bash
# Step 1: Create missing records and fill data
python scrubber.py \\
  --in raw_catalog.csv \\
  --log step1.log \\
  --create-missing \\
  --fill \\
  --dupe-size \\
  --prefer "NGC,IC,PK,UGC,Pal,Sharpless,RCW,vdB,Abell,Arp,Caldwell,Barnard,Messier" \\
| \\
# Step 2: Deduplicate and delete catalogs
python scrubber.py \\
  --out final_catalog.csv \\
  --log step2.log \\
  --dedupe-from "UGC,PGC,ESO" \\
  --keep "NGC,IC,Messier,Caldwell,Abell,Barnard,Sharpless"

# Step 3: Generate statistics
python scrubber.py \\
  --in final_catalog.csv \\
  --statistics
\`\`\`

## Best Practices

### Catalog Priority Order

Recommended priority order based on data quality:

\`\`\`
--prefer "NGC,IC,PK,UGC,Pal,Sharpless,RCW,vdB,Abell,Arp,Caldwell,Barnard,Messier"
\`\`\`

**Rationale:**
- NGC/IC: Professional catalogs with accurate coordinates
- PK (Planetary Nebula Catalog): Specialized, highly accurate
- Messier: Historical catalog, less precise coordinates

### Operation Sequence

**For best results, run operations in this order:**

1. **--create-missing** first to establish complete reference graph
2. **--fill** to populate data from cross-references
3. **--dupe-size** to ensure size field consistency
4. **--dedupe-from** to remove duplicates
5. **--keep** last to filter final output

### Logging Strategy

**Use --log for complex operations:**
\`\`\`bash
python scrubber.py \\
  --in input.csv \\
  --out output.csv \\
  --log operation.log \\
  --create-missing \\
  --fill \\
  --prefer "NGC,IC,Messier"
\`\`\`

**Review log files for:**
- Number of missing records created
- Number of bidirectional references added
- Number of target-source pairs modified
- Data overwrite reports (when higher priority sources overwrite existing data)
- Number of records deduplicated

### Incremental Processing

**For large datasets, use piping to separate concerns:**

\`\`\`bash
# First: Prepare data
python scrubber.py \\
  --in huge_catalog.csv \\
  --create-missing \\
  --fill \\
  --prefer "NGC,IC,Messier" \\
> prepared.csv

# Then: Filter and deduplicate
python scrubber.py \\
  --in prepared.csv \\
  --out final.csv \\
  --dedupe-from "UGC,PGC" \\
  --keep "NGC,IC,Messier"
\`\`\`

## Common Issues and Solutions

### Issue: Data Not Filling

**Symptom:** Fields remain empty after --fill

**Causes:**
1. Missing bidirectional references
2. Referenced objects don't have data either
3. Prefer list preventing overwrite

**Solutions:**
\`\`\`bash
# Always run --create-missing before --fill
python scrubber.py \\
  --in input.csv \\
  --out output.csv \\
  --create-missing \\
  --fill \\
  --prefer "NGC,IC,Messier"

# Check log to verify references were created
python scrubber.py \\
  --in input.csv \\
  --log debug.log \\
  --create-missing
\`\`\`

### Issue: Unexpected Deduplication

**Symptom:** Wrong records deleted

**Cause:** Incorrect --dedupe-from or --prefer order

**Solution:**
\`\`\`bash
# List catalogs you want DELETED in --dedupe-from
# List catalogs in accuracy order in --prefer
python scrubber.py \\
  --in input.csv \\
  --out output.csv \\
  --prefer "NGC,IC,Messier" \\
  --dedupe-from "UGC,PGC"  # Only UGC and PGC can be deleted
\`\`\`

### Issue: Broken Pipe When Piping

**Symptom:** \`BrokenPipeError\` when piping to commands like \`head\`

**Cause:** Downstream command closes pipe early

**Solution:** This is normal and handled internally. The error is caught and suppressed.

\`\`\`bash
# This is fine - broken pipe handled gracefully
python scrubber.py --in data.csv | head -20
\`\`\`

## Advanced Usage

### Multi-Stage Processing

**Process different catalog groups separately:**

\`\`\`bash
# Process NGC/IC group
cat all_data.csv \\
| python scrubber.py --keep "NGC,IC" \\
| python scrubber.py \\
    --create-missing \\
    --fill \\
    --prefer "NGC,IC" \\
> ngc_ic_processed.csv

# Process Messier group
cat all_data.csv \\
| python scrubber.py --keep "Messier" \\
| python scrubber.py \\
    --create-missing \\
    --fill \\
> messier_processed.csv

# Merge and deduplicate
# see merge.py to do this an easier way
cat ngc_ic_processed.csv messier_processed.csv \\
| python scrubber.py \\
    --out final.csv \\
    --dedupe-from "Messier" \\
    --prefer "NGC,IC,Messier"
\`\`\`

### Validation Workflow

**Validate data before and after processing:**

\`\`\`bash
# Before processing
python scrubber.py --in input.csv --statistics > before_stats.txt

# Process
python scrubber.py \\
  --in input.csv \\
  --out output.csv \\
  --create-missing \\
  --fill \\
  --prefer "NGC,IC,Messier"

# After processing
python scrubber.py --in output.csv --statistics > after_stats.txt

# Compare
diff before_stats.txt after_stats.txt
\`\`\`

### Data Quality Enhancement

**Comprehensive data enhancement pipeline:**

\`\`\`bash
python scrubber.py \\
  --in raw_data.csv \\
  --log enhance.log \\
  --create-missing \\
  --fill \\
  --dupe-size \\
  --prefer "NGC,IC,PK,UGC,Pal,Sharpless,RCW,vdB,Abell,Arp,Caldwell,Barnard,Messier" \\
| python scrubber.py \\
  --out enhanced_data.csv \\
  --dedupe-from "UGC,PGC,ESO,CGCG" \\
  --keep "NGC,IC,Messier,Caldwell,Abell,Barnard,Sharpless,PK"
\`\`\`

## Technical Notes

### Catalog Name Consistency

Catalog names must be consistent throughout:
- Database field: "Sharpless"
- --prefer list: "Sharpless"
- --keep list: "Sharpless"
- --dedupe-from list: "Sharpless"

### Field Name Case Sensitivity

Field names are case-sensitive:
- "Object" (not "object")
- "Catalogue" (not "catalog")
- "Other" (not "other")
- "Size_min" (not "size_min")
- "Size_max" (not "size_max")

### Performance Considerations

**For very large catalogs (100,000+ records):**
- Use --log to track progress
- Consider splitting into smaller batches
- Use piping to break into stages
- Filter early with --keep to reduce data volume

### Memory Usage

The script loads entire CSV into memory. For catalogs with:
- <50,000 records: No issues
- 50,000-200,000 records: Moderate memory usage (1-2 GB)
- >200,000 records: Consider batch processing

## Version History

- **Current**: Added stdin/stdout support, --dupe-size, bidirectional references in --create-missing
- **Previous**: TSV to CSV migration, improved deduplication logic

## Support

For issues or questions about scrubber.py, refer to:
- Log files for operational details
- Statistics output for data quality metrics
- This documentation for usage examples
`,

    'target-database': `# Target Database

The target database was compiled from two primary sources - the Saguaro
Astronomy Club Deep Sky Database and the OpenNGC database compiled by
Mattia Verga. The OpenNGC database also contains the IC catalogue.

Additional target sources were located in various places and merged into a
single database. As part of the compilation into a single database, a
program merged duplicate entries in a smart way such that no data
was lost.

However, many targets do not have a complete set of data. For example
hundreds of targets have neither a minimum nor maximum angular size. Thus,
they will not be included in the results when the size filter is used.

If a target has a maximum size but not a minumum, and vice-versa, the size
value was copied into the other field. Thus, some objects may seem as if
they are circular even if they are not. For the purposes of the database,
however, this is fine.

The following statistics are accurate as of 13 January 2026.

## Size statistics

    * Total Targets: 14,592
    * Targets with missing size values: 860
    * Targets with valid size values: 13,732

Note that of the 860 objects without size values, almost 92% are either
single stars or multiple star systems. An additional 13 are asteroids. Here
is the breakdown of those objects without size values

    * Stars: 790
    * Emission nebulae: 33
    * Open cluster: 19
    * Asteroids: 13
    * Dark nebulae: 3
    * Quasar: 1 (APM 08279+5255)
    * Supernova remnant: 1 (NGC 6974)

Smallest target

\`\`\`
IC 5117 (IC catalog)
Size: 0.02 arcminutes (1.2 arcseconds)
Type: Planetary nebula
\`\`\`

Largest target

\`\`\`
Sh 2-312 (Sharpless catalog)
Size: 720 arcminutes (12 degrees!)
Type: Emission nebula
\`\`\`

## Size distribution (arcminutes)

The vast majority of targets are small:

    * 0-1 arcmin: 4,775 targets (34.8%) 95.5% galaxies
    * 1-2 arcmin: 5,286 targets (38.5%) 94.7% galaxies
    * 2-3 arcmin: 1,389 targets (10.1%) 89.8% galaxies

83.4% of all targets are under 3 arcminutes. Larger targets become
increasingly rare.

    * 3-10 arcmin: 1,594 targets (11.6%) 51.9% galaxies
    * 10-30 arcmin: 438 targets (3.2%) 
    * 30-100 arcmin: 170 targets (1.2%)
    * 100+ arcmin: 80 targets (0.6%)

The distribution drops off dramatically after 10 arcminutes, with only
scattered large objects like nebulae complexes and extended structures
making up the tail end of the distribution.

## Target type distribution

Galaxies completely dominate the small object categories (under 3 arcmin),
representing over 94% of targets. Objects under 10 arcminutes in size are
90% galaxies.

As objects get larger, the percentage of galaxies drops dramatically, with
most large extended objects being nebulae or star clusters rather than
galaxies. There are only 117 galaxies or galaxy clusters that are larger
than 10 arcminutes. However, some are very large and make magnificant
imaging targets.

Here is the distribution of all types:

    * Asteroid: 13
    * Emission nebulae: 303
    * Cluster with nebulosity: 77
    * Dark nebulae: 304
    * Galaxy cluster: 315
    * Galaxy: 11,441
    * Globular cluster: 273
    * Open cluster: 720
    * Planetary nebula: 231
    * Quasar: 1
    * Reflection nebulae: 48
    * Supernova remnant: 20
    * Stars: 846

## How to use this information

Unless you are looking for small galaxies, you may choose to always set a
minimum size filter to exclude them. It's helpful to always select the
type(s) of targets you wish to image to avoid being overwhelmed with
galaxies.

You can use the "Create Imaging Program" capability in the Filter Results
to save the results of a filter rather than have to repeatedly perform the
same query.
`,

    'tutorial': `# Tutorial

Specula is a tool to help the astrophotographer develop a target list, plan
imaging sessions, and maintain an imaging log. It does not require an
internet connection. It is designed to be easy to use, fast, and
helpful.

This tutorial will step you through the various functions and capabilities
available. 

## User Interface

![Target Selection](images/full-target-selection.png "Target Selection")
 
 The User Interface (UI) is divided into two sections. On the left is the
 sidebar that allows you to access the menu, set the theme, set your
 location, and select one of the functions. The right side is the area
 where you enter parameters and view results.
 
## Sidebar

Clicking the hamburger menu opens up a menu.

    * Settings: Set Daylight Saving Time mode, Maximum Search Results for
      the Target Search, and the global minimum altitude setting. The
      global minimum altitude is the altitude at which you would begin to
      image and so it affects multiple other functions and calculations
      such as target rise and set times. 
    * Admin Tools >> Calculate Best Months: For the specified location(s), calculates the
      "Best Month" for observing each target and the range of months that
      the target is visible for at least two continuous dark hours. Depending on
      the speed of your computer, this calculation takes between 30 and 60
      seconds for each location. 
    * Admin Tools >> Manage Equipment: Add your telescopes, sensors, and filters.
    * Admin Tools >> Manage Observer Locations. Add, edit, or delete
      observer locations. You can add a horizon file to each location if
      desired. You can type or paste a list of azimuth/elevation numbers,
      one to a line in the format "<az> <el>". Try AngleCam for Android to
      generate the pairs. There are similar apps for the iPhone. Once a
      horizon file is defined for a location, you can include it in your
      visibility and sequence planning.
    * Admin Tools >> Clear All Targets: This completely zeroizes the target database (but
      not the Imaging Log database) in preparation for importing a new
      target CSV file. A "normal" user should never have to do this, but
      rely on backups in JSON format.
    * Admin Tools >> Merge New Targets: Import a target CSV file. A "normal" user should
      never have to do this, but rely on backups in JSON format.
    * Backup/Restore: Backup the database in JSON format and Restore
      a backup. Backup the Imaging Log in JSON format and restore
      it.
    * Help: A list of help documents.
    * About: Brief description and acknowledgements.
    
In the sidebar, click the top dropdown to select the theme style you wish
to use. Click the next dropdown to select the location you wish to use for
planning.

Next is a vertical list of buttons with the functions, operations, and
charts used to build a list of imaging targets and plan how and when to
image them.

## Target Selection

This view has multiple sections for searching, filtering, and remembering
(pinning) targets. From this page, you can do a free-text search (Target
Search) or Filter Targets based on five criteria. This view also has a
section to display your Pinned Targets. Pinned Targets are used when
planning an imaging sequence.

**Target Search**. Type in free-text in the search field. This can be a
complete or partial catalog identifier, common names such as 'Andromeda',
etc. As you type the list will populate dynamically up to the maximum
number defined in Settings. Click on the result to select that target. A
subset of metadata populates the section. You "Pin" the displayed target
from this screen with the list of all pinned targets displayed below the
target search section. Additional metadata is displayed by clicking the
Detail button. From the Detail screen, you can add (or remove) the target
to your "To Do" list, which is the list of targets that you wish to image
in the future.
      
**Filter Targets**. Use the dropdowns to filter the targets based on the
five criteria of catalog, type, month, minimum angular size, and maximum
magnitude. The Type catalogs are familiar except for Extra and Minor
Planet. The Extra category is a hodgepodge of various targets from various
sources and catalogs. I created the Extra category to condense multiple
sparse catalogs into a single one. Minor Planet is a list of interesting
and observable asteroids. Note that coordinates for minor planets are not
available in this tool.

The Type filter is all target types available in the tool. The Month filter
checks to see if the target is visible in that month. Other filters include
minimum angular size in arc-minutes and maximum magnitude. When you set the
filters and hit Apply, the results appear in the Filter Results
section. You can scroll through the results. Select a target by clicking
it.

In the Filter Results section is a "Create Imaging Program" button. This is
a feature in the Imaging Log section that you use to track targets you are
imaging from a list. By creating an image program from this view, you can
essentially save a filter setting and track as you image each target.

## To Do List

Displays the list of targets on your To Do list in various formats and
sorted by different criteria. These options are:

    * Rise Time chart. Shows the riset/set times of all the
      targets, if visible, tonight sorted by rise time.
    * Rise Time List. A text list of targets sorted by rise time.
    * Type. Sorted by the type of target.
    * Best Month. Sorted by the month determined to be the "best month" to
      observe it. The Yearly Observability function provides additional
      information about the best months to observe.

## Daily Visibility

Calculates and makes available to the user daily visibility charts and
information for the selected target. You specify the different filters and
settings in the Daily Visibility Parameters dialog box. A list of daily
visibility charts will be output and you select the one you want to
see. The charts are a graphical depiction of astronomical dusk/dawn, moon
rise/set, and target rise/set. If the target rises above the minimum
altitude/horizon line, the altitude curve will be displayed along with a
gradient background depicting how dark it will be from noon to noon of the
specified day. The visibility score takes into account moon illumination,
angle of the target to the moon, and target altitude.

## Yearly Observability 

For the selected target, displays a chart of the best times to image the
target over the next 12 months. After setting the minimum altitude (or
using the default global value from Settings), a gradient chart is
displayed depicting the best times/months to view.

## Field of View

Using the telescopes and sensors you entered from the Admin Tools >> Manage
Equipment page, the FOV function provides a notional field of view
containing the selected target. Note that not all targets have angular
sizes and that there are no background images. This tool simply provides a
general view of how a target might fill your FOV.

## Sequence Planner

Use this function to plan an imaging sequence for all your pinned targets
for a given night. This one has lots of settings. Using the settings
values, Sequence Planner attempts to help you plan out your most productive
evening across multiple targets, taking into account autofocus,
calibration, meridian flips durations. It initially optimizes based on
transit time, but you can drag and drop the targets into any order in the
Target Allocation section. Use the Target Allocation sliders to decrease
and increase the number of exposures to take for a given target. The other
targets dynamically adjust. At the bottom of the view is the Imaging Plan
section that translates the sequencing chart into potential start/top times
and an estimated number of exposures per target.

## Imaging Log

Allows you to keep track of Projects and Programs. 

### Projects

A Project is a series of one or more Imaging Sessions for a given
target. Create a new project by clicking the "+ New Project" button and
enter the data. It will search the target database as you enter your
targets. You may be focusing on a single target but once you get done,
there will be other targets in your field of view. You can come back and
add the additional targets to track them as well as the primary target.

Each Project has at least one session. These are typically a single night's
viewing. Create a session by opening the Imaging Sessions toggle and
selecting "+ Add Session" button. Enter the data you wish to preserve. Some
fields are required. Clicking "Calculate Moon Data" automagically fills in
the Moon fields. Data from the sessions is summarized at the project level
and displayed under the project name.

### Programs

Also on the Imaging Logs view is the Programs tab. You can create one or
more Imaging programs to track your progress based on your individual
goals. As mentioned earlier, you can create a Program from the Target
Filter view that saves the results of the filter into a new Program.

There are two types of Programs. After clicking "New Program", you select
whether the program is "Catalog Pattern" or "Manual List". Catalog Pattern
means that it draws targets from only one Catalog. You can specify the
number of items you wish to include from a single catalog.

The other type is "Manual List". Here you type or paste a list of
targets. When trying to save the program, it checks for invalid
entries. Within a Manual List, you can enter as many targets from as many
catalogs as you wish.

When you set the status of a Project to Complete, the targets are
automagically added to every Program that they match with. The Programs
page shows a horizontal progress bar.

### Reports

The Reports page on the Imaging Log view provides more details on the
status of both Projects and Programs. These include summary of catalog
targets captured, the ability to see which targets you've imaged for each
Program. For Manual List programs, you can also view the targets you have
not yet imaged. And finally, a Project Status summary report.

### Important 

Note that Imaging Log data is stored separately from the target
database. You can backup and restore it from the system menu.
`,

    'yearly-observability': `# Yearly Observability

The graph visualizes peak target altitude during astronomical darkness
throughout the year. The background gradient shows the observability
score for each day based on:

- How close the transit is to midnight
- Dark hours available (total time above type-specific threshold)

Darker shading indicates better observing conditions.
- **Black/very dark**: Excellent - target transits near midnight, maximum dark hours, new moon
- **Medium gray**: Good - target observable but moon present or transit offset
- **Light gray**: Marginal - limited dark hours or unfavorable moon
- **White**: Poor/impossible - target too low or sun interference


## Reading the Graph

- **Red/coral line**: Target's peak altitude during darkness each night
- **Dashed red line**: Your minimum altitude threshold (adjustable)
- **Background gradient**: Darker = better observing conditions
- **Yellow circles**: Full moon dates
- **Vertical orange line**: Today's date


## Controls

- **Minimum Altitude slider**: Set your personal minimum (affects dashed line only, not scoring)


## The Key Insight

Every target reaches its absolute maximum altitude every single night of
the year when it transits (crosses the meridian). This is determined purely
by geometry - its declination and your latitude. This never changes. But
the graph shows **peak** altitude during astronomical darkness and that can
vary, hence the flat sections and the descending/ascending sections.


## Flat section

Transit occurs at different times during the year. For example, at a
certain location a target might transit around 11pm in October, close to
midnight in December, and around 1am in February. All these times are
within astronomical darkness so the graph shows the peak altitude - the
target's full potential. The result is a flat line at maximum altitude.


## Descending curve

As you move past the optimal season (e.g., winter into spring), the target
transits progressively earlier. For example, the target might transit at
midnight in December, 8pm in February, and 4pm in April. In December and
February, these times are well within astronomical darkness, showing the
full altitude. By April, the target transits at 4pm - before darkness even
begins around 8pm. By the time it's dark enough, the target has already
passed its peak and is descending, it's altitude decreasing. The graph
shows a descending curve as darkness catches the target after its peak.


## Ascending curve

As you move away from the optimal season (e.g., late summer into fall), the
target transits progressively earlier into the night. For example, it might
transit at 8am in August, 6am in September, and 4am in October. In August,
darkness ends around 5am, so the target is still rising when darkness ends,
below its peak altitude. By October, darkness extends to 6am, so the target
transits at 4am during darkness, reaching its full 73° altitude. The graph
shows an ascending curve as progressively more of the target's rising arc
is captured within darkness.


## Bottom line

- Flat section = "target's transit happens during darkness."
- Sloped sections = "darkness only catches before or after a transit."


## How to use the graph

- Identify your imaging season (flat section = prime time)
- Plan around moon phases (dark areas between yellow circles)
- Understand why targets aren't visible certain months
- Compare transit timing preferences vs. moon avoidance
`,

};
